@rem 1G1
..\Release\TC_C_416_v912.exe 1.java
@rem 1G2
..\Release\TC_C_416_v912.exe 2.java
@rem 1G3
..\Release\TC_C_416_v912.exe 3.java
@rem 1G4
..\Release\TC_C_416_v912.exe 4.java
@rem 1G5
..\Release\TC_C_416_v912.exe long.java
@rem _BFilename
..\Release\TC_C_416_v912.exe thisfilenameistoolongandwillcauseaintegeroverflowwhenwetrytocountthenumberofcharactersinthisnamethisfilenameistoolongandwillcauseaintegeroverflowwhenwetrytocountthenumberofcharactersinthisname.java
@rem _1B
..\Release\TC_C_416_v912.exe thisfilenameistoolongandwillcauseaintegeroverflowwhenwetrytocountthenumberofcharactersinthisnamethisfilenameistoolongandwillcauseaintegeroverflowwhenwetrytocountthenumberofcharactersinthisname.java